/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentChatPanel: typeof import('./../components/workspace/AgentChatPanel.vue')['default']
    AgentResourcePanel: typeof import('./../components/workspace/AgentResourcePanel.vue')['default']
    AgentsPanel: typeof import('./../components/agent/AgentsPanel.vue')['default']
    AgentWorkbenchPanel: typeof import('./../components/workspace/AgentWorkbenchPanel.vue')['default']
    AIGenerate: typeof import('./../components/common/AIGenerate.vue')['default']
    BaseButton: typeof import('./../components/Form/BaseButton.vue')['default']
    ChatPanel: typeof import('./../components/agent/ChatPanel.vue')['default']
    CheckboxInput: typeof import('./../components/Form/CheckboxInput.vue')['default']
    ConfirmContainer: typeof import('./../components/Confirm/ConfirmContainer.vue')['default']
    Container: typeof import('./../components/Container.vue')['default']
    ContextMenu: typeof import('./../components/common/ContextMenu.vue')['default']
    ContextMenuItem: typeof import('./../components/common/ContextMenuItem.vue')['default']
    ContextPanel: typeof import('./../components/agent/ContextPanel.vue')['default']
    DangerButton: typeof import('./../components/Form/DangerButton.vue')['default']
    ErrorDisplay: typeof import('./../components/common/ErrorDisplay.vue')['default']
    FileTreeNode: typeof import('./../components/agent/FileTreeNode.vue')['default']
    GhostButton: typeof import('./../components/Form/GhostButton.vue')['default']
    HTMLPreview: typeof import('./../components/agent/preview/HTMLPreview.vue')['default']
    ImageViewer: typeof import('./../components/agent/preview/ImageViewer.vue')['default']
    LoadingOverlay: typeof import('./../components/LoadingOverlay.vue')['default']
    MarkdownEditor: typeof import('./../components/MarkdownEditor.vue')['default']
    MarkdownPreview: typeof import('./../components/agent/preview/MarkdownPreview.vue')['default']
    MessageContainer: typeof import('./../components/Message/MessageContainer.vue')['default']
    ModelSelector: typeof import('./../components/ModelSelector.vue')['default']
    OutlineButton: typeof import('./../components/Form/OutlineButton.vue')['default']
    OverlayMask: typeof import('./../components/OverlayMask/index.vue')['default']
    PDFViewer: typeof import('./../components/agent/preview/PDFViewer.vue')['default']
    Popover: typeof import('./../components/Popover/Popover.vue')['default']
    PopoverContainer: typeof import('./../components/Popover/PopoverContainer.vue')['default']
    Popup: typeof import('./../components/Popup/index.vue')['default']
    PrimaryButton: typeof import('./../components/Form/PrimaryButton.vue')['default']
    ProjectPanel: typeof import('./../components/agent/ProjectPanel.vue')['default']
    RadioInput: typeof import('./../components/Form/RadioInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./../components/Form/SecondaryButton.vue')['default']
    SelectInput: typeof import('./../components/Form/SelectInput.vue')['default']
    StatusBar: typeof import('./../components/StatusBar.vue')['default']
    SwitchInput: typeof import('./../components/Form/SwitchInput.vue')['default']
    TerminalPanel: typeof import('./../components/agent/TerminalPanel.vue')['default']
    TextButton: typeof import('./../components/Form/TextButton.vue')['default']
    TextInput: typeof import('./../components/Form/TextInput.vue')['default']
    ToolTipContainer: typeof import('./../components/ToolTip/ToolTipContainer.vue')['default']
    Versions: typeof import('./../components/Versions.vue')['default']
    VideoPlayer: typeof import('./../components/agent/preview/VideoPlayer.vue')['default']
    VoicePanel: typeof import('./../components/agent/VoicePanel.vue')['default']
    WorkbenchPanel: typeof import('./../components/agent/WorkbenchPanel.vue')['default']
  }
}
