/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIGenerate: typeof import('./../components/common/AIGenerate.vue')['default']
    BaseButton: typeof import('./../components/Form/BaseButton.vue')['default']
    CheckboxInput: typeof import('./../components/Form/CheckboxInput.vue')['default']
    ConfirmContainer: typeof import('./../components/Confirm/ConfirmContainer.vue')['default']
    Container: typeof import('./../components/Container.vue')['default']
    ContextMenu: typeof import('./../components/common/ContextMenu.vue')['default']
    ContextMenuItem: typeof import('./../components/common/ContextMenuItem.vue')['default']
    DangerButton: typeof import('./../components/Form/DangerButton.vue')['default']
    ErrorDisplay: typeof import('./../components/common/ErrorDisplay.vue')['default']
    GhostButton: typeof import('./../components/Form/GhostButton.vue')['default']
    LoadingOverlay: typeof import('./../components/LoadingOverlay.vue')['default']
    MessageContainer: typeof import('./../components/Message/MessageContainer.vue')['default']
    OutlineButton: typeof import('./../components/Form/OutlineButton.vue')['default']
    OverlayMask: typeof import('./../components/OverlayMask/index.vue')['default']
    Popover: typeof import('./../components/Popover/Popover.vue')['default']
    PopoverContainer: typeof import('./../components/Popover/PopoverContainer.vue')['default']
    Popup: typeof import('./../components/Popup/index.vue')['default']
    PrimaryButton: typeof import('./../components/Form/PrimaryButton.vue')['default']
    RadioInput: typeof import('./../components/Form/RadioInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./../components/Form/SecondaryButton.vue')['default']
    SelectInput: typeof import('./../components/Form/SelectInput.vue')['default']
    StatusBar: typeof import('./../components/StatusBar.vue')['default']
    SwitchInput: typeof import('./../components/Form/SwitchInput.vue')['default']
    TextButton: typeof import('./../components/Form/TextButton.vue')['default']
    TextInput: typeof import('./../components/Form/TextInput.vue')['default']
    ToolTipContainer: typeof import('./../components/ToolTip/ToolTipContainer.vue')['default']
    Versions: typeof import('./../components/Versions.vue')['default']
  }
}
